# Generated by Django 3.0.4 on 2020-04-19 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0003_auto_20200402_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='descricao_mini',
        ),
    ]
