# Generated by Django 3.0.4 on 2020-04-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0004_remove_anuncio_descricao_mini'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='imagem',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
